image:
  collectdExporter:
    repository: prom/collectd-exporter
    tag: "0.3.1"
    pullPolicy: IfNotPresent

common:
  extraLabels:

collectdExporter:
  auth:
    login: changeme
    password: secretpassword
  extraLabels:
  service:
    loadBalancerIP: ""

global:
  extraLabels:
# monitoring in the global scope
  monitoring:
    enabled: true
    namespace: monitoring
    extraLabels:
