apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "collectd-exporter.fullName" . }}-config"
  labels:
    app: {{ template "collectd-exporter.fullName" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "collectd-exporter.fullName" . }}
    prometheus: "{{ .Values.global.monitoring.namespace }}"
    {{- range $key, $value := .Values.global.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := .Values.common.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := .Values.collectdExporter.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
data:
  auth_file: |-
    {{ printf "%s: %s" .Values.collectdExporter.auth.login .Values.collectdExporter.auth.password | b64enc }}
