apiVersion: v1
kind: Service
metadata:
  name: {{ template "collectd-exporter.fullName" . }}-metrics
  labels:
    app: {{ template "collectd-exporter.fullName" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "collectd-exporter.fullName" . }}
    role: collectd-exporter
    {{- range $key, $value := .Values.global.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := .Values.common.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := .Values.collectdExporter.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    component: {{ template "collectd-exporter.fullName" . }}
    role: collectd-exporter
  ports:
    - name: collectd-exporter
      port: 9103
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "collectd-exporter.fullName" . }}-input
  labels:
    app: {{ template "collectd-exporter.fullName" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "collectd-exporter.fullName" . }}
    role: collectd-exporter
    {{- range $key, $value := .Values.global.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := .Values.common.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := .Values.collectdExporter.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.collectdExporter.service.loadBalancerIP }}
  selector:
    component: {{ template "collectd-exporter.fullName" . }}
    role: collectd-exporter
  ports:
  - name: collectd
    port: 25826
    protocol: UDP
