{{- if .Values.global.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "collectd-exporter.fullName" . }}-rules
  labels:
    prometheus: "{{ .Values.global.monitoring.namespace }}"
    app: {{ template "collectd-exporter.fullName" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "collectd-exporter.fullName" . }}
    role: collectd-exporter
    {{- range $key, $value := .Values.global.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := .Values.common.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := .Values.collectdExporter.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
data:
  collectd.rules: |-
        groups:
        - name: ./collectd.rules
          rules:
          - alert: collectd-exporter Down
            expr: collectd_last_push_timestamp_seconds == 0 or absent(collectd_exporter_build_info == 1)
            for: 10m
            labels:
              severity: warning
            annotations:
              description: Prometheus could not scrape a colectd-exporter for more than 10m,
                or collectd-exporter have disappeared from discovery.
              summary: collectd-exporter cannot be scraped
{{- end }}
