apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "collectd-exporter.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: "{{ template "collectd-exporter.fullname" . }}-config"
data:
  auth_file: {{ include "auth_file.tpl" . | b64enc }}
