apiVersion: v1
kind: Service
metadata:
  name: {{ template "collectd-exporter.fullname" . }}-input
  labels:
    app: {{ template "collectd-exporter.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}" 
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
  - name: collectd
    port: 25826
    protocol: UDP
  selector:
    name: collectd-exporter

 
